theme: jekyll-theme-minimal
title: hairdesign homepage
description: Bookmark this to keep an eye on my project updates!
domain: 
url: https://anigerra.github.io/hairdesign-web
baseurl: /hairdesign-web/
